package Coordinate.coordikittyBE.domain.closet.enums;

public class Category {
    // 대분류
    public enum Large {OUTER, TOPS, BOTTOMS, SKIRTS, ONEPIECE, SHOES}

    public enum Medium {
        HOODED_ZIP_UP, BLOUSON, BLAZER, CARDIGAN, COAT, WIND_BREAKER, PADDING,
        TOPS_LONG, TOPS_SHORT, LESS,
        BOTTOMS_LONG, BOTTOMS_SHORT,
        SKIRTS_LONG, MIDI, MINI
    }
        // 중분류
        public enum OUTER {HOODED_ZIP_UP, BLOUSON, BLAZER, CARDIGAN, COAT, WIND_BREAKER, PADDING}
        public enum TOPS {LONG, SHORT, LESS}
        public enum BOTTOMS {LONG, SHORT}
        public enum SKIRTS {LONG, MIDI, MINI}

    public enum Small {
        HOODED_ZIP_UP, BLOUSON, CARDIGAN, BLAZER, SINGLE, TRENCH, WIND_BREAKER, LONG, SHORT,

        TOPS_LONG_NEAT, TOPS_LONG_HOODED, TOPS_LONG_SWEAT, TOPS_LONG_SHIRTS, TOPS_LONG_T_SHIRTS, TOPS_LONG_SPORTS,
        TOPS_SHORT_POLO, TOPS_SHORT_SHIRTS, TOPS_SHORT_SWEAT, TOPS_SHORT_T_SHIRTS, TOPS_SHORT_SPORTS,
        LESS,

        BOTTOMS_LONG_DENIM, BOTTOMS_LONG_SLACKS, BOTTOMS_LONG_SWEAT, BOTTOMS_LONG_CARGO, BOTTOMS_LONG_LEGGINGS, BOTTOMS_LONG_COTTON, BOTTOMS_LONG_SPORTS,
        BOTTOMS_SHORT_DENIM, BOTTOMS_SHORT_SWEAT, BOTTOMS_SHORT_COTTON, BOTTOMS_SHORT_SPORTS,

        SKIRTS_LONG_LAB, SKIRTS_LONG_FLARE, SKIRTS_LONG_MERMAID,
        MIDI_H, MIDI_A, MIDI_PLEATS, MIDI_FLARE, MIDI_K,
        MINI_H, MINI_A, MINI_LAB, MINI_FLARE
    }
        // 소분류
        public enum HOODED_ZIP_UP {HOODED_ZIP_UP}
        public enum BLOUSON {BLOUSON}
        public enum CARDIGAN {CARDIGAN}
        public enum BLAZER {BLAZER}
        public enum COAT {SINGLE, TRENCH}
        public enum WIND_BREAKER {WIND_BREAKER}
        public enum PADDING {LONG, SHORT}

        public enum TOPS_LONG {NEAT, HOODED, SWEAT, SHIRTS, T_SHIRTS, SPORTS}
        public enum TOPS_SHORT {POLO, SHIRTS, SWEAT, T_SHIRTS, SPORTS}
        public enum LESS {LESS}

        public enum BOTTOMS_LONG {DENIM, SLACKS, SWEAT, CARGO, LEGGINGS, COTTON, SPORTS}
        public enum BOTTOMS_SHORT {DENIM, SWEAT, COTTON, SPORTS}

        public enum SKIRTS_LONG {LAB, FLARE, MERMAID}
        public enum MIDI {H, A, PLEATS, FLARE, K}
        public enum MINI {H, A, LAB, FLARE}
}
