package Coordinate.coordikittyBE.domain.closet.enums;

public enum Large {
    OUTER, TOPS, BOTTOMS, ONEPIECE, SKIRTS, SHOES
}

enum OUTER {
    HOODED_ZU, BLOUSON, LEATHER_RIDERS, MUSTANG, TRUCkER, SUIT_BLAZER, CARDIGAN, ANORAK, FLEECE, TRAINING, STADIUM, TRANSITIONAL, SINGLE_COAT, DOUBLE_COAT, OTHER_COAT, LONG_PUFFER, SHORT_PUFFER, PADDED_VEST, VEST, SAFARI_HUNTING, NYLON_COACH, OTHER
}

enum TOPS {
    KNIT, HOODED, SWEATSHIRT, LONG_SLEEVE, SHIRT, PIQUE, SHORT_SLEEVE, SPORTS, OTHER
}

enum BOTTOMS {
    DENIM, COTTON, SUIT, TRAINING, SHORTS, LEGGINGS, JUMPSUITS, SPORTS, OTHER
}

enum ONEPIECE {
    MINI, MIDI, MAXI
}

enum SKIRTS {
    MINI, MIDI, LONG
}

enum SHOES {
    CANVAS, FASHION, SPORTS, LOAFERS, HEELS, FLAT, BLOATERS, SANDALS, SLIPPERS, MOCCASINS, BOOTS, OTHER
}