spring:
  #  datasource:
  #    url: jdbc:mysql://coordikitty-develop.cf8kwgwi0zw7.ap-northeast-2.rds.amazonaws.com:3306/coordikitty-develop
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: admin
  #    password: qwer1234
  datasource:
    url: ${AWS_URL}
    driver-class-name: ${AWS_DRIVER_CLASS_NAME}
    username: ${AWS_USERNAME}
    password: ${AWS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  issuer: master
  secret_key: 37d5fc606779aa85f1b693a734a1fdd9621d97d91a4a2f929aaf0f2b6a23c903