spring:
  #  datasource:
  #    url: jdbc:mysql://coordikitty-develop.cf8kwgwi0zw7.ap-northeast-2.rds.amazonaws.com:3306/coordikitty-develop
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: admin
  #    password: qwer1234
  datasource:
    url: jdbc:mysql://coordikitty-develop.cf8kwgwi0zw7.ap-northeast-2.rds.amazonaws.com:3306/coordikitty-develop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 482387727195-pu5htji2hv3bbj1b0ce8e7edaqcs0mb7.apps.googleusercontent.com
            client-secret: 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
jwt:
  issuer: master
  secret_key: 37d5fc606779aa85f1b693a734a1fdd9621d97d91a4a2f929aaf0f2b6a23c903
