name: coordikitty CD with gradle

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Compare branch 코드 내려 받기
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # 2. 자바 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Firebase를 위한 JSON 파일 생성
      - name: Create Json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "./src/main/resources/coordikitty-firebase-adminsdk-1ld5i-ca22d4f0a5.json"
          json: ${{ secrets.FIREBASE_PRODUCTION_JSON }}
#        env:
#          AWS_RDS_URL_DEVELOP: ${{ secrets.AWS_RDS_URL_DEVELOP }}
#          AWS_RDS_DRIVER: ${{ secrets.AWS_RDS_DRIVER }}
#          AWS_RDS_USERNAME: ${{ secrets.AWS_RDS_USERNAME }}
#          AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
#          REDIS_HOST: ${{ secrets.REDIS_HOST }}
#          REDIS_PORT: ${{ secrets.REDIS_PORT }}
#          OAUTH2_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
#          OAUTH2_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
#          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
#          JWT_SECRET: ${{ secrets.JWT_SECRET }}
#          JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
#          JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
#          OPENWEATHERMAP_KEY: ${{ secrets.OPENWEATHERMAP_KEY }}
#          FCM_KEY: ${{ secrets.FCM_KEY }}
#          LOCAL_DOMAIN: ${{ secrets.LOCAL_DOMAIN }}
#          SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}

      - name: make application-dev.yml
        run: |
          cd ./src/main/resources

          touch ./application-dev.yml

          echo "${{ secrets.DEV }}" >> ./application-dev.yml

        shell: bash
      # 3. Docker 이미지 build 및 push
      - name: docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coordikitty:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/coordikitty:latest

      # 4. ec2 pull
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/coordikitty:latest
            docker stop coordikitty:latest
            docker rm coordikitty:latest
            docker run --name coordikitty:latest -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/sponjy-app-server